FROM alpine:edge AS build
RUN apk add --no-cache --update go gcc g++ git 
WORKDIR /app/
COPY . .
RUN go env -w GOPROXY=direct
RUN CGO_ENABLED=1 GOOS=linux go build -o main cmd/server/main.go

FROM alpine:edge
COPY --from=build /app/main  /app/main
CMD ["/app/main"]